apiVersion: v1
kind: Service
metadata:
  name: smartgrid-wechat-portal
spec:
  selector:
    app: smartgrid-wechat-portal
  type: NodePort
  ports:
     - port: 3011
       targetPort: 3011
       nodePort: 3012
