apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: smartgrid-wechat-portal
  name: smartgrid-wechat-portal
  namespace: gridvo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: smartgrid-wechat-portal
    spec:
      containers:
      - name: smartgrid-wechat-portal
        image: 10.0.3.31:5000/gridvo/smartgrid-wechat-portal:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3150
        - containerPort: 3011
        volumeMounts:
        - name: keys-path
          mountPath: "/home/keys"
          readOnly: true
        env:
        - name: DATA_COLLECT_SERVICE_HOST
          value: "data-collect"
        - name: DATA_COLLECT_SERVICE_PORT
          value: "80"
        - name: DATA_QUERY_SERVICE_HOST
          value: "data-query"
        - name: DATA_QUERY_SERVICE_PORT
          value: "80"
        - name: DATA_VISUAL_SERVICE_HOST
          value: "data-visual"
        - name: DATA_VISUAL_SERVICE_PORT
          value: "80"
        - name: SMARTGRID_LESSEE_SERVICE_HOST
          value: "smartgrid-lessee"
        - name: SMARTGRID_LESSEE_SERVICE_PORT
          value: "80"
        - name: ZOOKEEPER_SERVICE_HOST
          value: "zookeeper"
        - name: ZOOKEEPER_SERVICE_PORT
          value: "2181"
        - name: ZIPKIN_SERVICE_HOST
          value: "zipkin"
        - name: ZIPKIN_HTTP_TRANSPORT_PORT
          value: "9411"
        - name: SSL_KEY_PATH
          value: "/home/keys/gridvocomrsa.key"
        - name: SSL_CA_PATH
          value: "/home/keys/1_root_bundle.crt"
        - name: SSL_CERT_PATH
          value: "/home/keys/1_www.gridvo.com_bundle.crt"
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
      volumes:
      - name: keys-path
        hostPath:
          path: "/var/gridvo/keys"
