apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartgrid-wechat-portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smartgrid-wechat-portal
    spec:
      containers:
      - name: smartgrid-wechat-portal
        image: 10.0.2.62:5000/gridvo/smartgrid-wechat-portal:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3150
        - containerPort: 3011
        volumeMounts:
        - name: keys-path
          mountPath: "/home/keys"
          readOnly: true
        env:
        - name: SSL_KEY_PATH
          value: "/home/keys/gridvocomrsa.key"
        - name: SSL_CA_PATH
          value: "/home/keys/1_root_bundle.crt"
        - name: SSL_CERT_PATH
          value: "/home/keys/1_www.gridvo.com_bundle.crt"
        - name: ZK_TRACER_HTTP
          value: "true"
        - name: IS_DEBUG
          value: "true"
      volumes:
      - name: keys-path
        hostPath:
          path: "/var/keys"
