apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartgrid-wechat-portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smartgrid-wechat-portal
    spec:
      containers:
      - name: smartgrid-wechat-portal
        image: 10.0.2.62:5000/gridvo/smartgrid-wechat-portal:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 3150
        - containerPort: 3011
        env:
        - name: ZK_TRACER_HTTP
          value: "true"
             
