apiVersion: v1
kind: Service
metadata:
  labels:
    name: smartgrid-wechat-portal
  name: smartgrid-wechat-portal
  namespace: gridvo
spec:
  selector:
    name: smartgrid-wechat-portal
  type: NodePort
  ports:
     - port: 3011
       targetPort: 3011
       nodePort: 31013
